### ISSUE TITLE
Small typo mistakes on your site

### ISSUE THREAD

**Issue by adamsthws** [Puliczek/github-achievements-academy#1071]
Hello, thankyou kindly for making your usefull guide!

I noticed a couple of small spelling / word mistakes on the guide...

- Under `How to get Galaxy Brain`
  - the word 'answet' should be 'answer'.

- Under `How to get Public Sponsor`:
  - 'you just got an Starstruck achievement!' should be 'you just got an Public Sponsor achievement!'

**Comment by Puliczek** [comment]
I am glad that you like it :)

Thanks for the report. I just pushed an update :)
