### ISSUE TITLE
Typo in the githubachievements.com HTML at the How to get Galaxy Brain section.

### ISSUE THREAD

**Issue by fka-kafka** [Puliczek/github-achievements-academy#994]
Hi Maciej Pulikowski,

I noticed a small typo and some grammatical errors in the [githubachievements](https://githubachievements.com) website HTML at the [How to get Galaxy Brain](https://githubachievements.com/#galaxy-brain-section) section. 
The current text is: 
```
1. Find an unanswered question and answer the question, remember to answer correctly! Also your answet must be selected as the submitted answer by owner of the question
2. Reach 2 submitted answers in any categories
```

While it should be:
```
1. Find an unanswered question and answer the question, remember to answer correctly! Also your answer must be selected as the accepted answer by owner of the question
2. Reach 2 accepted answers in any category
```

Please allow me access to the file so that I can contribute those changes.

**Comment by Puliczek** [comment]
Hi @fka-kafka,

Thanks for the report. I just fixed it and pushed it to production.

I am planning to open-source the whole website and publish it here, but I don't have time right now :(

Thanks again! :)

**Comment by fka-kafka** [comment]
Should you want an extra pair of hands during the process, I would be more than happy to contribute in any way
